### ISSUE TITLE
Error "openFile: does not exist" when creating interactive snippets.

### ISSUE THREAD

**Issue by anka-213** [co-dan/interactive-diagrams#32]
When trying to compile any interactive snippet (for example [this](http://paste.hskll.org/get/2439)) I get the following error:

    /home/vagrant/.ghcjs/i386-linux-0.1.0-7.7.20130922/settings: openFile: does not exist (No such file or directory)

**Comment by co-dan** [comment]
Sorry about that, for some reason a directory with ghcjs files got unmounted on one of the workers. Should be fixed now.
